Create fr_fr.json
SlimeKnights/Mantle pull request #155
Opened 2021-05-15 16:00 UTC by Aarrn33

I added a french localisation

2022-01-02 19:11 UTC, Aspyro requested changes

2022-01-02 19:11 UTC, Aspyro commented on src/main/resources/assets/mantle/lang/fr_fr.json
> +  "command.mantle.tag_collection.not_found": "Collecirion '%s' d'étiquettes inconnue",
Typo : ~~Collecirion~~ -> Collection

2022-01-02 19:11 UTC, Aspyro commented on src/main/resources/assets/mantle/lang/fr_fr.json
> +  "command.mantle.view_tags.no_targeted_tile_entity": "Pas de fluide dans la zone",
Translation "dans la zone" (*in the zone*) would be more precise if switched with "à portée" (*in range*).

2022-01-02 19:11 UTC, Aspyro commented on src/main/resources/assets/mantle/lang/fr_fr.json
> +  "command.mantle.view_tags.no_tags": "Pas d'étiquette",
Linked with keys `"command.mantle.view_tags.(...)"` but should be `"command.mantle.tags_for.(...)"`.

2022-01-02 19:11 UTC, Aspyro commented on src/main/resources/assets/mantle/lang/fr_fr.json
> +  "command.mantle.dump_all_tags.type_success": "Toutes les étiquettes %s de '%s' ont été mise",
Literal (and better) translation would be `"Toutes les étiquettes de %s ont été mises dans '%s'"`

2022-01-03 11:06 UTC, Aspyro commented
I believe now it can be merged. It fully translates the file `en_us.json`.

2022-01-31 18:25 UTC, merged

2022-01-31 19:29 UTC, Aarrn33 commented
Thanhs